runmode: test                 # 开发模式, debug, release, test
port: :8003                  # HTTP绑定端口
name: ginserver              # API Server的名字
url: http://127.0.0.1:8003   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数

db:
  name: order
  addr: 127.0.0.1:3306
  username: root
  password: Marykay1
